import type { Account } from "./types";

export const ACCOUNTS: Account[] = [
  {
    id: "bny",
    name: "BNY Mellon",
    industry: "Banking & Financial Services",
    region: "AMS",
    arrTotal: 2400000,
    renewalDate: "2026-06-30",
    rag: "amber",
    lastQbrDate: "2025-11-15",
    lastContactDate: "2026-03-01",
    execSponsorTungsten: "Victoria Hawkins",
    execSponsorCustomer: "Sarah Chen (CTO)",
    revenue: [
      { pillar: "Document & Workflow Automation", product: "TotalAgility", arrCurrent: 1200000, contractEndDate: "2026-06-30", contractType: "SAAS" },
      { pillar: "Document & Workflow Automation", product: "Capture", arrCurrent: 300000, contractEndDate: "2026-06-30", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "AP Essentials", arrCurrent: 450000, contractEndDate: "2026-06-30", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "Invoices", arrCurrent: 250000, contractEndDate: "2026-06-30", contractType: "SAAS" },
      { pillar: "PDF & eSignature", product: "Power PDF", arrCurrent: 200000, contractEndDate: "2026-09-15", contractType: "Subscription" },
    ],
    intelligence: {
      ownershipType: "global",
      keyProblems: "Legacy TotalAgility version (7.x) — not on current platform. Trade finance modernization stalled due to internal AI governance review. Procurement pushing back on price increases.",
      usageRate: 72,
      satisfactionRating: 3,
      satisfactionNotes: "Functional but not delighted. Key sponsor supportive; IT team frustrated with upgrade complexity.",
      geographiesServed: ["North America", "EMEA", "APAC"],
      relationships: [
        { type: "Business Sponsor", contact: "Sarah Chen (CTO)", status: "strong", notes: "Champions Tungsten internally. Quarterly calls." },
        { type: "IT", contact: "Mark Polowski (VP IT)", status: "developing", notes: "Engaged on upgrade path. Cautious." },
        { type: "Infosec", contact: "Unknown", status: "gap", notes: "No relationship established. Blocker for cloud migration." },
        { type: "AI Lab/COE", contact: "Dr. Priya Nair", status: "developing", notes: "Interested in agentic AI use cases. Early conversations." },
        { type: "Procurement", contact: "James Thornton", status: "developing", notes: "Price sensitivity. Needs strong business case." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2025-09-10",
      strategyPlays: ["renew_early", "move_up", "expand_use_case"],
      strategyNotes: "Priority is early renewal before June 30. Upgrade to TA 8.x is the move-up play. Expand into new trade finance use cases with Dr. Nair's team.",
      pipelineAlignment: "$2.4M renewal + $400K expansion opportunity in SFDC. Stage 3 (Proposal). Target close Q1 FY27.",
      helpNeeded: "Need executive top-to-top meeting with CEO. Infosec relationship is a blocker — need Customer Success support for security review.",
      completenessScore: 78,
    },
    signals: [
      { type: "renewal_approaching", detail: "Renewal in 104 days (June 30, 2026)", date: "2026-03-18" },
      { type: "contact_gap", detail: "No Infosec contact established", date: "2026-03-18" },
    ],
  },
  {
    id: "jpmorgan",
    name: "JPMorgan Chase",
    industry: "Banking & Financial Services",
    region: "AMS",
    arrTotal: 3800000,
    renewalDate: "2026-09-30",
    rag: "green",
    lastQbrDate: "2026-02-20",
    lastContactDate: "2026-03-10",
    execSponsorTungsten: "Victoria Hawkins",
    execSponsorCustomer: "David Park (SVP Operations)",
    revenue: [
      { pillar: "Document & Workflow Automation", product: "TotalAgility", arrCurrent: 2000000, contractEndDate: "2026-09-30", contractType: "SAAS" },
      { pillar: "Document & Workflow Automation", product: "Transformation", arrCurrent: 500000, contractEndDate: "2026-09-30", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "Process Director", arrCurrent: 900000, contractEndDate: "2026-09-30", contractType: "SAAS" },
      { pillar: "Print & Workplace Automation", product: "ControlSuite", arrCurrent: 400000, contractEndDate: "2027-03-31", contractType: "Subscription" },
    ],
    intelligence: {
      ownershipType: "global",
      keyProblems: "Scaling automation to 40+ business units globally. Want AI-native document processing for loan origination. Exploring competitor solutions for KYC automation.",
      usageRate: 89,
      satisfactionRating: 4,
      satisfactionNotes: "Strong advocate. High utilization. Pushing for more AI capability.",
      geographiesServed: ["North America", "EMEA", "APAC", "Latin America"],
      relationships: [
        { type: "Business Sponsor", contact: "David Park (SVP Operations)", status: "strong", notes: "Annual summit participant. Monthly calls." },
        { type: "IT", contact: "Rachel Kim (Enterprise Architect)", status: "strong", notes: "Deep technical relationship. Co-designing roadmap." },
        { type: "Infosec", contact: "Tom Brady (CISO)", status: "developing", notes: "Met once. Need to deepen." },
        { type: "AI Lab/COE", contact: "Dr. Amir Hassan", status: "strong", notes: "Joint AI roadmap session planned for Q2." },
        { type: "Procurement", contact: "Linda Torres", status: "strong", notes: "Multi-year relationship. Responsive." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2026-01-15",
      strategyPlays: ["multi_year", "expand_division", "expand_use_case"],
      strategyNotes: "Lock in multi-year deal at renewal. Expand into loan origination and KYC use cases with AI Lab. Protect against competitive threat.",
      pipelineAlignment: "$3.8M renewal + $800K expansion. Stage 4 (Negotiation). Target close Q2 FY27.",
      helpNeeded: "Need VE ROI assessment for loan origination expansion. Deal Desk support for multi-year pricing.",
      completenessScore: 92,
    },
    signals: [
      { type: "expansion_ready", detail: "AI Lab joint session planned — loan origination & KYC expansion opportunity", date: "2026-03-18" },
    ],
  },
  {
    id: "fujifilm",
    name: "FujiFilm",
    industry: "Technology & Manufacturing",
    region: "APAC",
    arrTotal: 1100000,
    renewalDate: "2026-05-15",
    rag: "red",
    lastQbrDate: "2025-08-10",
    lastContactDate: "2026-01-22",
    execSponsorTungsten: "Victoria Hawkins",
    execSponsorCustomer: "Kenji Tanaka (IT Director)",
    revenue: [
      { pillar: "Document & Workflow Automation", product: "TotalAgility", arrCurrent: 700000, contractEndDate: "2026-05-15", contractType: "SAAS" },
      { pillar: "Print & Workplace Automation", product: "ControlSuite", arrCurrent: 250000, contractEndDate: "2026-05-15", contractType: "Subscription" },
      { pillar: "PDF & eSignature", product: "Power PDF", arrCurrent: 150000, contractEndDate: "2026-05-15", contractType: "Subscription" },
    ],
    intelligence: {
      ownershipType: "regional",
      keyProblems: "Low usage of TotalAgility — estimated 40% capacity utilization. No executive champion since Yamamoto-san retired. Budget under pressure. Evaluating competitive alternatives.",
      usageRate: 40,
      satisfactionRating: 2,
      satisfactionNotes: "At-risk. IT team frustrated. Business sponsor vacuum since Q3 2025.",
      geographiesServed: ["Japan", "APAC"],
      relationships: [
        { type: "Business Sponsor", contact: "Vacant", status: "gap", notes: "Previous sponsor Yamamoto-san retired Sept 2025. No replacement identified." },
        { type: "IT", contact: "Kenji Tanaka (IT Director)", status: "developing", notes: "Operational relationship only. Not strategic." },
        { type: "Infosec", contact: "Unknown", status: "gap", notes: "No relationship." },
        { type: "AI Lab/COE", contact: "Unknown", status: "gap", notes: "No relationship." },
        { type: "Procurement", contact: "Yuki Sato", status: "developing", notes: "Cost reduction mandate. Difficult conversations expected." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2025-06-01",
      strategyPlays: ["renew_early", "expand_relationships"],
      strategyNotes: "URGENT: Renewal in 58 days with no exec sponsor. Need to identify new champion immediately. Adoption program required to demonstrate value before renewal.",
      pipelineAlignment: "$1.1M renewal at risk. No active opportunity in SFDC. Must create urgency.",
      helpNeeded: "Need SE Lead to fly to Tokyo. Customer Success adoption intervention. Executive introduction from Tungsten CRO.",
      completenessScore: 42,
    },
    signals: [
      { type: "renewal_approaching", detail: "URGENT: Renewal in 58 days (May 15). No exec sponsor. Low usage.", date: "2026-03-18" },
      { type: "contact_gap", detail: "Business sponsor vacant since Sept 2025. No Infosec or AI Lab contact.", date: "2026-03-18" },
    ],
  },
  {
    id: "usbank",
    name: "US Bancorp",
    industry: "Banking & Financial Services",
    region: "AMS",
    arrTotal: 1850000,
    renewalDate: "2026-12-31",
    rag: "green",
    lastQbrDate: "2026-01-30",
    lastContactDate: "2026-03-05",
    execSponsorTungsten: "Barry McErlean",
    execSponsorCustomer: "Jennifer Walsh (EVP Operations)",
    revenue: [
      { pillar: "Document & Workflow Automation", product: "TotalAgility", arrCurrent: 950000, contractEndDate: "2026-12-31", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "AP Essentials", arrCurrent: 500000, contractEndDate: "2026-12-31", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "Process Director", arrCurrent: 400000, contractEndDate: "2026-12-31", contractType: "SAAS" },
    ],
    intelligence: {
      ownershipType: "global",
      keyProblems: "Moving to cloud-first architecture. Legacy on-prem TA deployment needs modernization roadmap. AP team wants faster invoice processing SLAs.",
      usageRate: 81,
      satisfactionRating: 4,
      satisfactionNotes: "Strong relationship. Pushing for cloud migration plan.",
      geographiesServed: ["North America"],
      relationships: [
        { type: "Business Sponsor", contact: "Jennifer Walsh (EVP Operations)", status: "strong", notes: "Executive champion. Board-level visibility." },
        { type: "IT", contact: "Carlos Rivera (VP Infrastructure)", status: "strong", notes: "Cloud migration partner." },
        { type: "Infosec", contact: "Amy Chen (CISO)", status: "developing", notes: "Cloud security review underway." },
        { type: "AI Lab/COE", contact: "Unknown", status: "gap", notes: "AI program in early stages — no contact yet." },
        { type: "Procurement", contact: "Steve Morrison", status: "strong", notes: "Supportive. Multi-year deal history." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2026-02-10",
      strategyPlays: ["multi_year", "move_up", "expand_use_case"],
      strategyNotes: "Lock in 3-year deal before year-end. Move Up to cloud TA. Expand into AI-powered invoice exception handling.",
      pipelineAlignment: "$1.85M renewal + $300K Move Up expansion. Stage 2 (Discovery). Target close Q3 FY27.",
      helpNeeded: "VE assessment for cloud ROI. Product team roadmap briefing for AI invoice features.",
      completenessScore: 82,
    },
    signals: [
      { type: "expansion_ready", detail: "Cloud migration creates Move Up opportunity — TA on-prem to cloud", date: "2026-03-18" },
    ],
  },
  {
    id: "tdbank",
    name: "TD Bank",
    industry: "Banking & Financial Services",
    region: "AMS",
    arrTotal: 2100000,
    renewalDate: "2027-03-31",
    rag: "green",
    lastQbrDate: "2026-02-15",
    lastContactDate: "2026-03-12",
    execSponsorTungsten: "Barry McErlean",
    execSponsorCustomer: "Michael O'Brien (CTO)",
    revenue: [
      { pillar: "Document & Workflow Automation", product: "TotalAgility", arrCurrent: 1400000, contractEndDate: "2027-03-31", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "Invoices", arrCurrent: 400000, contractEndDate: "2027-03-31", contractType: "SAAS" },
      { pillar: "Document & Workflow Automation", product: "Capture", arrCurrent: 300000, contractEndDate: "2027-03-31", contractType: "SAAS" },
    ],
    intelligence: {
      ownershipType: "global",
      keyProblems: "100M+ annual target deal in progress. Integration with internal AI program 'Eliza'. Regulatory pressure on AI governance and audit trails.",
      usageRate: 85,
      satisfactionRating: 4,
      satisfactionNotes: "Strategic partner relationship. TD sees Tungsten as infrastructure for their AI program.",
      geographiesServed: ["North America", "EMEA"],
      relationships: [
        { type: "Business Sponsor", contact: "Michael O'Brien (CTO)", status: "strong", notes: "Executive champion at CTO level." },
        { type: "IT", contact: "Patricia Lee (VP Architecture)", status: "strong", notes: "Co-designing Eliza integration." },
        { type: "Infosec", contact: "Robert Chen (CISO)", status: "strong", notes: "AI governance alignment meeting completed." },
        { type: "AI Lab/COE", contact: "Dr. Fatima Al-Hassan", status: "strong", notes: "Deep engagement on Eliza x Tungsten architecture." },
        { type: "Procurement", contact: "Kevin Murphy", status: "developing", notes: "100M deal in negotiation. Complex terms." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2026-03-01",
      strategyPlays: ["expand_use_case", "expand_division", "multi_year"],
      strategyNotes: "100M+ deal is the primary focus. Position as AI plumbing for Eliza program. Expand across all TD divisions.",
      pipelineAlignment: "100M+ strategic deal in SFDC. Stage 4 (Negotiation). Highest priority account.",
      helpNeeded: "Deal Desk for complex pricing. Legal for enterprise terms. Executive alignment at CEO level.",
      completenessScore: 95,
    },
    signals: [
      { type: "expansion_ready", detail: "100M+ strategic deal in active negotiation — highest priority account", date: "2026-03-18" },
    ],
  },
  {
    id: "citi",
    name: "Citibank",
    industry: "Banking & Financial Services",
    region: "AMS",
    arrTotal: 1650000,
    renewalDate: "2026-08-31",
    rag: "amber",
    lastQbrDate: "2025-12-05",
    lastContactDate: "2026-02-18",
    execSponsorTungsten: "Victoria Hawkins",
    execSponsorCustomer: "Alexandra Ross (MD Operations)",
    revenue: [
      { pillar: "AP & AR Automation", product: "AP Essentials", arrCurrent: 700000, contractEndDate: "2026-08-31", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "Process Director", arrCurrent: 550000, contractEndDate: "2026-08-31", contractType: "SAAS" },
      { pillar: "Document & Workflow Automation", product: "TotalAgility", arrCurrent: 400000, contractEndDate: "2026-08-31", contractType: "SAAS" },
    ],
    intelligence: {
      ownershipType: "global",
      keyProblems: "Trade finance modernization (VE case study delivered Oct 2025). Competing internal team building custom solution. Need to demonstrate ongoing value.",
      usageRate: 68,
      satisfactionRating: 3,
      satisfactionNotes: "Satisfied with trade finance results but cautious about expanding further.",
      geographiesServed: ["North America", "EMEA", "APAC", "Latin America"],
      relationships: [
        { type: "Business Sponsor", contact: "Alexandra Ross (MD Operations)", status: "strong", notes: "Published success story with us." },
        { type: "IT", contact: "Unknown", status: "gap", notes: "No IT relationship at senior level." },
        { type: "Infosec", contact: "Unknown", status: "gap", notes: "No relationship." },
        { type: "AI Lab/COE", contact: "Unknown", status: "gap", notes: "Internal AI team is the competition." },
        { type: "Procurement", contact: "Brian Walsh", status: "developing", notes: "Renewal discussions begin Q2." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2025-10-20",
      strategyPlays: ["renew_early", "expand_use_case", "expand_relationships"],
      strategyNotes: "Renew before internal team gains momentum. Need to engage AI Lab — position Tungsten as complements their build, not competes. Expand trade finance success to other regions.",
      pipelineAlignment: "$1.65M renewal. Stage 2. Internal competition is risk factor.",
      helpNeeded: "VE engagement to quantify trade finance ROI achieved. Need to counter internal build narrative.",
      completenessScore: 61,
    },
    signals: [
      { type: "renewal_approaching", detail: "Renewal in 166 days (Aug 31). Internal team building competing solution.", date: "2026-03-18" },
    ],
  },
  {
    id: "nhs-wales",
    name: "NHS Wales",
    industry: "Healthcare & Public Sector",
    region: "EMEA",
    arrTotal: 420000,
    renewalDate: "2026-11-30",
    rag: "green",
    lastQbrDate: "2026-01-10",
    lastContactDate: "2026-02-28",
    execSponsorTungsten: "Conor O'Neill",
    execSponsorCustomer: "Dr. Helen Morgan (CDIO)",
    revenue: [
      { pillar: "Document & Workflow Automation", product: "TotalAgility", arrCurrent: 280000, contractEndDate: "2026-11-30", contractType: "SAAS" },
      { pillar: "Document & Workflow Automation", product: "Capture", arrCurrent: 140000, contractEndDate: "2026-11-30", contractType: "SAAS" },
    ],
    intelligence: {
      ownershipType: "regional",
      keyProblems: "NHS digital transformation mandate. Expanding document automation to patient records and referrals. Budget cycles tied to UK government spending reviews.",
      usageRate: 91,
      satisfactionRating: 5,
      satisfactionNotes: "Excellent. High utilization. Strong advocate. Reference customer.",
      geographiesServed: ["UK - Wales"],
      relationships: [
        { type: "Business Sponsor", contact: "Dr. Helen Morgan (CDIO)", status: "strong", notes: "Public sector champion. Speaking at NHS Digital conference." },
        { type: "IT", contact: "Gareth Evans (Head of IT)", status: "strong", notes: "Technical champion." },
        { type: "Infosec", contact: "Owen Roberts", status: "strong", notes: "Cyber Essentials certified. Good relationship." },
        { type: "AI Lab/COE", contact: "Unknown", status: "gap", notes: "NHS AI program just launched." },
        { type: "Procurement", contact: "Susan Phillips", status: "strong", notes: "Framework contract. Smooth renewal process." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2026-01-10",
      strategyPlays: ["expand_use_case", "expand_geo", "multi_year"],
      strategyNotes: "Expand to other NHS Wales trusts. Patient records and referral automation is the next use case. Position as NHS AI infrastructure.",
      pipelineAlignment: "$420K renewal + $150K expansion to patient records. Stage 2.",
      helpNeeded: "Public sector pricing framework. Case study for NHS reference. Introduction to NHS England team.",
      completenessScore: 88,
    },
    signals: [
      { type: "expansion_ready", detail: "NHS AI program launched — opportunity to position as NHS AI infrastructure", date: "2026-03-18" },
    ],
  },
  {
    id: "maritz",
    name: "Maritz",
    industry: "Business Services",
    region: "AMS",
    arrTotal: 380000,
    renewalDate: "2026-10-31",
    rag: "green",
    lastQbrDate: "2025-11-20",
    lastContactDate: "2026-02-10",
    execSponsorTungsten: "Thomas Jacob",
    execSponsorCustomer: "Chris Davidson (CFO)",
    revenue: [
      { pillar: "AP & AR Automation", product: "AP Essentials", arrCurrent: 240000, contractEndDate: "2026-10-31", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "Process Director", arrCurrent: 140000, contractEndDate: "2026-10-31", contractType: "Subscription" },
    ],
    intelligence: {
      ownershipType: "regional",
      keyProblems: "AP process transformation delivered strong ROI (published case study). Looking to expand to AR automation and expense management.",
      usageRate: 95,
      satisfactionRating: 5,
      satisfactionNotes: "Highly satisfied. Published case study. CFO is an active reference.",
      geographiesServed: ["North America"],
      relationships: [
        { type: "Business Sponsor", contact: "Chris Davidson (CFO)", status: "strong", notes: "Reference customer. Speaks at Tungsten events." },
        { type: "IT", contact: "Mike Thompson", status: "strong", notes: "Strong technical relationship." },
        { type: "Infosec", contact: "Unknown", status: "gap", notes: "No formal relationship but no issues." },
        { type: "AI Lab/COE", contact: "Unknown", status: "unknown", notes: "Small company — likely no formal AI program." },
        { type: "Procurement", contact: "Chris Davidson (CFO)", status: "strong", notes: "CFO owns procurement for Tungsten." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2025-11-20",
      strategyPlays: ["expand_use_case", "cross_sell"],
      strategyNotes: "Expand to AR automation. Cross-sell PDF & eSignature for contract management. Easy win given satisfaction level.",
      pipelineAlignment: "$380K renewal + $100K AR expansion. Stage 1 (Identified).",
      helpNeeded: "VE assessment for AR expansion ROI. Co-present CFO reference at banking conference.",
      completenessScore: 79,
    },
    signals: [
      { type: "expansion_ready", detail: "High satisfaction + high utilization — AR automation expansion opportunity", date: "2026-03-18" },
    ],
  },
  {
    id: "apple",
    name: "Apple",
    industry: "Technology",
    region: "AMS",
    arrTotal: 890000,
    renewalDate: "2026-07-31",
    rag: "amber",
    lastQbrDate: "2025-10-15",
    lastContactDate: "2026-01-30",
    execSponsorTungsten: "Barry McErlean",
    execSponsorCustomer: "James Liu (VP Operations Technology)",
    revenue: [
      { pillar: "Print & Workplace Automation", product: "ControlSuite", arrCurrent: 600000, contractEndDate: "2026-07-31", contractType: "Subscription" },
      { pillar: "PDF & eSignature", product: "Power PDF", arrCurrent: 290000, contractEndDate: "2026-07-31", contractType: "Subscription" },
    ],
    intelligence: {
      ownershipType: "global",
      keyProblems: "Print management contract renewal. Apple internally evaluating consolidation of print vendors. New procurement team with no relationship to Tungsten.",
      usageRate: 77,
      satisfactionRating: 3,
      satisfactionNotes: "Functional relationship. No strong advocate. Risk of procurement-led switch.",
      geographiesServed: ["North America", "EMEA", "APAC"],
      relationships: [
        { type: "Business Sponsor", contact: "James Liu (VP Operations Technology)", status: "developing", notes: "New contact post-reorg. Relationship being rebuilt." },
        { type: "IT", contact: "Unknown", status: "gap", notes: "No senior IT contact." },
        { type: "Infosec", contact: "Unknown", status: "gap", notes: "No relationship." },
        { type: "AI Lab/COE", contact: "Unknown", status: "unknown", notes: "Apple AI is entirely internal." },
        { type: "Procurement", contact: "Sarah Nakamura (new)", status: "developing", notes: "New procurement lead. No existing relationship with Tungsten." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2025-09-01",
      strategyPlays: ["renew_early", "expand_relationships", "consolidate_coterm"],
      strategyNotes: "Must establish relationship with new procurement lead before they complete vendor review. Early renewal play to lock in before review concludes. Co-term PDF & eSignature with ControlSuite.",
      pipelineAlignment: "$890K renewal. Stage 1. Risk of churn if procurement review goes against us.",
      helpNeeded: "Executive introduction to new procurement lead. Competitive intelligence on what other print vendors are proposing.",
      completenessScore: 52,
    },
    signals: [
      { type: "renewal_approaching", detail: "Renewal in 135 days. New procurement lead — relationship gap.", date: "2026-03-18" },
      { type: "contact_gap", detail: "No IT, Infosec, or senior contacts. New procurement lead uncontacted.", date: "2026-03-18" },
    ],
  },
  {
    id: "sps",
    name: "SPS Commerce",
    industry: "Supply Chain & Logistics",
    region: "AMS",
    arrTotal: 310000,
    renewalDate: "2027-01-31",
    rag: "green",
    lastQbrDate: "2025-12-10",
    lastContactDate: "2026-02-25",
    execSponsorTungsten: "Victoria Hawkins",
    execSponsorCustomer: "David Chen (COO)",
    revenue: [
      { pillar: "AP & AR Automation", product: "Invoices", arrCurrent: 200000, contractEndDate: "2027-01-31", contractType: "SAAS" },
      { pillar: "AP & AR Automation", product: "AP Essentials", arrCurrent: 110000, contractEndDate: "2027-01-31", contractType: "SAAS" },
    ],
    intelligence: {
      ownershipType: "regional",
      keyProblems: "Rapid growth driving invoice volume beyond current contract limits. Needs volume-based pricing review. Interested in knowledge discovery for supply chain documentation.",
      usageRate: 98,
      satisfactionRating: 5,
      satisfactionNotes: "At capacity. Growth story. Very happy with product.",
      geographiesServed: ["North America"],
      relationships: [
        { type: "Business Sponsor", contact: "David Chen (COO)", status: "strong", notes: "Champions Tungsten at industry events." },
        { type: "IT", contact: "Amanda Reyes", status: "strong", notes: "Technical lead. Highly engaged." },
        { type: "Infosec", contact: "Unknown", status: "gap", notes: "No formal relationship." },
        { type: "AI Lab/COE", contact: "Unknown", status: "unknown", notes: "No formal AI program." },
        { type: "Procurement", contact: "David Chen (COO)", status: "strong", notes: "COO owns procurement." },
      ],
      partnerOrDirect: "direct",
      partnerNotes: "",
      lastTopToTopDate: "2025-12-10",
      strategyPlays: ["expand_use_case", "cross_sell", "multi_year"],
      strategyNotes: "At 98% utilization — expansion is the natural next conversation. Knowledge discovery for supply chain docs is a strong new use case. Lock in multi-year deal.",
      pipelineAlignment: "$310K renewal + $150K expansion. Stage 2.",
      helpNeeded: "VE assessment for knowledge discovery use case. Volume pricing review with Deal Desk.",
      completenessScore: 81,
    },
    signals: [
      { type: "expansion_ready", detail: "98% utilization — contract volume expansion needed + knowledge discovery opportunity", date: "2026-03-18" },
    ],
  },
];

export function getAccount(id: string): Account | undefined {
  return ACCOUNTS.find((a) => a.id === id);
}

export function getAccountsSummary() {
  return ACCOUNTS.map((a) => ({
    id: a.id,
    name: a.name,
    industry: a.industry,
    region: a.region,
    arrTotal: a.arrTotal,
    renewalDate: a.renewalDate,
    rag: a.rag,
    lastContactDate: a.lastContactDate,
    signals: a.signals,
    completenessScore: a.intelligence.completenessScore,
    strategyPlays: a.intelligence.strategyPlays,
  }));
}
